Repository wazuh/wazuh-api, pull requests merged in 2018-10, with the labels that each got.

#178 Fix for '%' character error.
  controllers/index.js
Labels: bug

#171 Syscheck API calls
  controllers/experimental.js
  controllers/syscheck.js
  helpers/errors.js
  helpers/input_validation.js
  helpers/request_templates.js
  test/test_syscheck.js
Labels: enhancement

#182 API 3.7 documentation update
  controllers/ciscat.js
  controllers/experimental.js
  controllers/syscheck.js
  controllers/syscollector.js
Labels: enhancement

#191 Update API examples for generating documentation
  controllers/agents.js
  controllers/cluster.js
  doc/README.md
Labels: enhancement

#194 Remove extra parameters from GET/agents/:agent_id/config/:component/:configuration
  controllers/agents.js
  package.json
Labels: bug

#198 Update API documentation for 3.7 release
  controllers/agents.js
  controllers/cluster.js
  controllers/experimental.js
  doc/README.md
  doc/generate_rst.py
Labels: enhancement

#200 Update API test
  test/README.md
  test/test_agents.js
  test/test_agents_2.js
Labels: enhancement

#201 Fix for ppid filter in /syscollector/processes call
  controllers/experimental.js
  controllers/syscollector.js
Labels: bug, bugfix

#202 Update experimental mocha test
  test/test_agents.js
  test/test_syscollector.js
Labels: bug, enhancement

#204 Error code for invalid characters in array names was added.
  helpers/errors.js
Labels: bug, bugfix

#209 Fix for Node 5 compatibility
  controllers/agents.js
  helpers/request_templates.js
Labels: bug, enhancement

#213 API calls cluster/stats/remoted and cluster/stats/analysisd
  controllers/cluster.js
  test/test_cluster.js
Labels: enhancement

#214 Deny API calls in worker nodes
  app.js
  helpers/errors.js
  package.json
Labels: enhancement

#216 Fix healthcheck param validation
  controllers/cluster.js
Labels: bug, bugfix

#217 Fix agents filter by os.name
  controllers/agents.js
Labels: enhancement

#215 node filter was renamed to node_name
  controllers/agents.js
Labels: bug, bugfix

#229 Disable API on worker nodes
  app.js
  models/wazuh-api.py
Labels: enhancement

#230 Fix bug when multiple select parameters are used in the API query
  helpers/filters.js
Labels: bug

#231 Remove xml2json-light library
  package.json
Labels: bugfix
