Repository wazuh/wazuh-api, pull requests merged in 2019-07, with the labels that each got.

#404 Changed MD5 for BCrypt
  CHANGELOG.md
  scripts/configure_api.sh
Labels: enhancement

#414 Update purge docstring description
  controllers/agents.js
Labels: bugfix

#408 Fix API installation script for Docker
  install_api.sh
  scripts/install_daemon.sh
Labels: bugfix

#418 Fix docstring for lists.js GET lists/files
  controllers/lists.js
Labels: bug

#420 Fix GET /cluster/:node_id/stats/analysisd docstring
  controllers/cluster.js
Labels: bug
