Repository wazuh/wazuh-api, pull requests merged in 2019-02, with the labels that each got.

#301 Calls for getting CDB lists
  controllers/index.js
  controllers/lists.js
  test/test_lists.js
Labels: enhancement

#299 New call to edit files (rules, decoders, lists and ossec.conf)
  app.js
  controllers/index.js
  controllers/manager.js
  helpers/errors.js
  helpers/files.js
  helpers/filters.js
  package.json
  test/test_manager.js
Labels: enhancement

#278 Automated test environment and new tests
  .gitignore
  test/README.md
  test/data/agent.conf.xml
  test/data/invalid.conf.xml
  test/data/wrong.conf.xml
  test/environment/vagrant/Vagrantfile
  test/environment/vagrant/configure_manager.sh
  test/environment/vagrant/install_agent.sh
  test/environment/vagrant/ossec_agents.conf
  test/environment/vagrant/ossec_master.conf
  test/test_agents.js
  test/test_cluster.js
  test/test_rootcheck.js
  test/test_syscollector.js
Labels: bugfix, enhancement

#308 Edit files in cluster
  controllers/agents.js
  controllers/cluster.js
  controllers/manager.js
  helpers/files.js
  helpers/filters.js
  test/test_cluster.js
  test/test_manager.js
Labels: enhancement

#316 New mocha tests for worker nodes in cluster
  test/test_cluster.js
  test/test_manager.js
Labels: enhancement

#317 Update mocha test (manager)
  test/test_cluster.js
  test/test_manager.js
Labels: enhancement

#319 Add default value for older_than param
  controllers/agents.js
Labels: bugfix

#321 Dev rootcheck pm
  controllers/configuration_assessment.js
  controllers/index.js
  helpers/input_validation.js
  test/test_configuration_assessment.js
Labels: enhancement

#322 Update mocha tests
  test/test_configuration_assessment.js
  test/test_rootcheck.js
Labels: enhancement

#323 Mocha tests for agents were updated.
  test/test_agents.js
Labels: bugfix

#324 Fix mocha tests (syscollector)
  controllers/experimental.js
  test/test_syscollector.js
Labels: bug, bugfix

#328 New revision and renaming configuration assessment to sca
  CHANGELOG.md
  README.md
  controllers/index.js
  controllers/security_configuration_assessment.js
  package.json
  test/test_sca.js
Labels: enhancement

#330 Update regex for filtering paths
  helpers/filters.js
Labels: enhancement

#332 Enable API in worker nodes
  models/wazuh-api.py
Labels: enhancement
