Repository wazuh/wazuh-api, pull requests merged in 2019-01, with the labels that each got.

#265 Fix for getting ossec gid and uid with userid module
  helpers/logger.js
  package.json
Labels: bugfix

#257 API call for upgrading group configuration
  app.js
  controllers/agents.js
  controllers/index.js
  helpers/errors.js
  helpers/files.js
  helpers/filters.js
  helpers/input_validation.js
  install_api.sh
  package.json
Labels: enhancement

#266 Replace libxmljs by fast-xml-parser and bugfixes in custom install directories
  helpers/files.js
  helpers/filters.js
  models/wazuh-api.py
  package.json
Labels: bugfix, enhancement

#269 Update installation script
  install_api.sh
Labels: bugfix

#296 Fix improper error handling
  CHANGELOG.md
  app.js
  helpers/execute.js
Labels: bugfix, enhancement
