Repository wazuh/wazuh-api, pull requests merged in 2019-03, with the labels that each got.

#337 Overwrite parameter for uploading files
  controllers/cluster.js
  controllers/manager.js
  test/test_cluster.js
  test/test_manager.js
Labels: enhancement

#338 New call for deleting files
  controllers/cluster.js
  controllers/manager.js
  test/test_cluster.js
  test/test_manager.js
Labels: enhancement

#340 Add version filter to GET/experimental/syscollector/packages API call
  CHANGELOG.md
  controllers/experimental.js
Labels: enhancement

#344 Fix when empty path parameter is empty
  controllers/cluster.js
  controllers/manager.js
  helpers/errors.js
  test/test_cluster.js
  test/test_manager.js
Labels: bug, bugfix

#348 Fix download parameter (rules and decoders calls)
  helpers/response_handler.js
  test/test_decoders.js
  test/test_rules.js
Labels: bugfix

#353 Improve input validation of API queries
  helpers/errors.js
  helpers/input_validation.js
Labels: bugfix

#355 Fix for uploading CDB lists
  helpers/errors.js
  helpers/filters.js
  test/test_manager.js
Labels: bugfix

#357 New parameter (validation) for getting files
  controllers/cluster.js
  controllers/manager.js
  test/test_cluster.js
  test/test_manager.js
Labels: enhancement

#359 Fix bad input validation regex for q param
  helpers/input_validation.js
Labels: bugfix

#360 Add mocha test for POST/agents/restart API call
  test/test_agents.js
Labels: bugfix
