Repository wazuh/wazuh-api, pull requests merged in 2019-11, with the labels that each got.

#461 Add 'mitre' filter for rules
  controllers/rules.js
  test/test_rules.js
Labels: enhancement

#462 3.12 special character agent name
  helpers/errors.js
  helpers/input_validation.js
  test/test_agents.js
  test/test_agents_2.js
Labels: enhancement, operations

#463 Fix for agents mocha tests
  test/test_agents.js
Labels: bug
